spring:
  application:
    name:  spring-boot-project
  jpa:
    show-sql:  true
    hibernate:
#      ddl-auto:  create
  datasource:
    url: jdbc:mysql://localhost:3306/db2
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port:  8090
